name = "rh-lol"
version = "0.1.0"
keywords = ["math", "lean", "riemann-hypothesis"]
defaultTargets = ["RHLean"]
builtinLint = true
lintDriver = "batteries/runLinter"
lintDriverArgs = ["RHLean"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "RHLean"
